spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: ok
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full


logging:
  level:
    root: info
    com.zb.mapper: debug
  config: classpath:lombok-spring.xml
